namespace:
    core: src/tb/apps/content/plugins/
    demo: ~

core:
    contentselector:
        accept: ['*']
        config: []

    parameters:
        accept: ['*']
        config: []

    contentsetplus:
        accept: ['*']
        config: []

    remove:
        accept: ['*']
        config: []

    imagepicker:
        accept: ['*']
        config: []

    edition:
        accept: ['*']
        config: []

    dnd:
       accept: ['*']
       config: []

    rte:
        accept: ['*']
        config:
            adapter: 'cke'
            aloha:
                libPath: ''
            cke:
                libName: 'ckeeditor'
                skin: 'backbee,/resources/toolbar/src/tb/component/cke/skins/backbee/'
                editableConfig:
                    basic:
                        title: ''
                        toolbarGroups:
                            - {name: 'editing', groups: ['basicstyles', 'links']}
                            - {name: 'undo'}
                            - {name: 'clipboard', groups: ['selection', 'clipboard']}
                            - {name: 'about'}
                        removePlugins: 'colorbutton,find,flash,font,forms,iframe,newpage,removeformat,smiley,specialchar,stylescombo,templates'
                        removeButtons: 'About,Anchor'
                        extraAllowedContent: 'span(*)[id];div(*)[id];p(*)[id];h1(*)[id];h2(*)[id];h3(*)[id];h4(*)[id];h5(*)[id];ol(*)[id];ul(*)[id];li(*)[id]'
                    lite:
                        title: "lite editor"
                        toolbarGroups: []
                        removePlugins: 'colorbutton,specialchar,links'
                        removeButtons: 'About,Anchor'
                        extraAllowedContent: 'span(*)[id];div(*)[id];p(*)[id];h1(*)[id];h2(*)[id];h3(*)[id];h4(*)[id];h5(*)[id];ol(*)[id];ul(*)[id];li(*)[id]'
demo: []
