core:
    ApplicationManager:
        appPath: $resources-baseurl$/toolbar/src/tb/apps
        active: main
        route: ""
        applications:

            main:
                label: Main
                config:
                    mainRoute: appMain/index

            content:
                label: Edition du contenu
                config: []

            bundle:
                label: Bundle
                config:
                    mainRoute: bundle/index

            page:
                label: Page
                config:
                    mainRoute: page/index

            contribution:
                label: Contribution
                config:
                    mainRoute: contribution/index

            user:
                label: User
                config:
                    mainRoute: user/index
                scope:
                    global:
                        open: user.showCurrent

wrapper_toolbar_id: 'bb5-ui'

default_url: 'content/contribution/edit'

component:

    logger:
        level: 8
        mode: 'devel'

    exceptions-viewer:
        show: true
        showInConsole: true

    medialibrary:
        available_media:
          - {title: 'Image', type: 'Media/Image', ico: 'fa fa-picture'}
          - {title: 'Pdf', type: 'Media/Pdf', ico: 'fa fa-file-pdf-o'}

        add_to_library_map:
          'Element/Image':
            transform_into: 'Media/Image'
            title_element: title
            file_element: image

    translator:
        base: '$resources-baseurl$/toolbar/src/tb/i18n/'
        default_locale: 'en_US'
        locales:
            en_US: 'EN'
            fr_FR: 'FR'
            ru_RU: 'RU'

unclickable_contents:
    contents:
        - 'Element/Text'
        - 'Element/Attachment'
        - 'Element/Date'
        - 'Element/File'
        - 'Element/Keyword'
        - 'Element/Link'
        - 'Element/Select'
        - 'Element/Image'

contents_events:
    rules:
    - { type: 'Element/Image', target: 'parent', events: 'context'}